-- TABELA PARA INSERT DE DADOS PARA LOJAS--

INSERT INTO LOJAS (NOME, MORADA, FUNCIONARIOS) VALUES ('Loja 1', 'Rua A, Lisboa', 5);
INSERT INTO LOJAS (NOME, MORADA, FUNCIONARIOS) VALUES ('Loja 2', 'Rua B, Porto', 3);
INSERT INTO LOJAS (NOME, MORADA, FUNCIONARIOS) VALUES ('Loja 3', 'Rua C, Lisboa', 4);
INSERT INTO LOJAS (NOME, MORADA, FUNCIONARIOS) VALUES ('Loja 4', 'Rua D, Faro', 2);
INSERT INTO LOJAS (NOME, MORADA, FUNCIONARIOS) VALUES ('Loja 5', 'Rua E, Lisboa', 6);

-- TABELA PARA INSERT DE DADOS EM PECAS--
INSERT INTO PECAS (TIPO, COR, TAMANHO,URGENCIA) VALUES ('Camisa', 'Azul', 'M',1);
INSERT INTO PECAS (TIPO, COR, TAMANHO,URGENCIA) VALUES ('Casaco', 'Preto', 'L',1);
INSERT INTO PECAS (TIPO, COR, TAMANHO,URGENCIA) VALUES ('Calças', 'Branco', 'S',1);
INSERT INTO PECAS (TIPO, COR, TAMANHO,URGENCIA) VALUES ('Saia', 'Vermelho', 'M',0);
INSERT INTO PECAS (TIPO, COR, TAMANHO,URGENCIA) VALUES ('Vestido', 'Verde', 'XL',0);
INSERT INTO PECAS (TIPO, COR, TAMANHO,URGENCIA) VALUES ('Camisa', 'Azul,verde', 'M',1);
INSERT INTO PECAS (TIPO, COR, TAMANHO,URGENCIA) VALUES ('Casaco', 'Preto,branco', 'L',1);
INSERT INTO PECAS (TIPO, COR, TAMANHO,URGENCIA) VALUES ('Calças', 'Branco,preto', 'S',0);
INSERT INTO PECAS (TIPO, COR, TAMANHO,URGENCIA) VALUES ('Saia', 'Vermelho,roxo', 'M',1);
INSERT INTO PECAS (TIPO, COR, TAMANHO,URGENCIA) VALUES ('Vestido', 'Verde,branco', 'XL',0);

-- TABELA PARA INSERT DE DADOS EM ARRANJOS-
INSERT INTO ARRANJOS (TIPO, CUSTO) VALUES ('Coser', 10.00);
INSERT INTO ARRANJOS (TIPO, CUSTO) VALUES ('Bainhas de vestido', 5.00);
INSERT INTO ARRANJOS (TIPO, CUSTO) VALUES ('Colocar fechos', 15.00);
INSERT INTO ARRANJOS (TIPO, CUSTO) VALUES ('Aplicar botões', 8.00);
INSERT INTO ARRANJOS (TIPO, CUSTO) VALUES ('Ajustar tamanho', 12.00);

-- TABELA PARA INSERT DE DADOS EM PEDIDOS|CONCLUIDO=1 NAO CONCLUIDO=0 DEVOLVIDO=1 NAO DEVOLVIDO=0-- 
INSERT INTO PEDIDOS (LOJAID, CLIENTE, DATA_INICIO, DATA_FIM, CONCLUIDO, PAGO, URGENCIA, DEVOLVIDO, OBSERVACOES) VALUES (1, 'Cliente 1', '2022-06-01', '2023-06-12', 1, 1, 0, 1, 'peças sensíveis');
INSERT INTO PEDIDOS (LOJAID, CLIENTE, DATA_INICIO, DATA_FIM, CONCLUIDO, PAGO, URGENCIA, DEVOLVIDO, OBSERVACOES) VALUES (4, 'Cliente 2', '2022-07-22', '2023-06-11', 0, 0, 0, 0, 'peças sensíveis');
INSERT INTO PEDIDOS (LOJAID, CLIENTE, DATA_INICIO, DATA_FIM, CONCLUIDO, PAGO, URGENCIA, DEVOLVIDO, OBSERVACOES) VALUES (5, 'Cliente 3', '2023-10-01', '2023-06-10', 1, 0, 1, 1, 'N/A');
INSERT INTO PEDIDOS (LOJAID, CLIENTE, DATA_INICIO, DATA_FIM, CONCLUIDO, PAGO, URGENCIA, DEVOLVIDO, OBSERVACOES) VALUES (3, 'Cliente 4', '2023-06-01', '2023-06-09', 1, 0, 1, 0, 'peças sensíveis');
INSERT INTO PEDIDOS (LOJAID, CLIENTE, DATA_INICIO, DATA_FIM, CONCLUIDO, PAGO, URGENCIA, DEVOLVIDO, OBSERVACOES) VALUES (5, 'Cliente 2', '2023-06-01', '2023-06-11', 0, 0, 1, 1, 'peças sensíveis');


-- TABELA PARA INSERT DE DADOS EM PEDIDO POR PECAS--
INSERT INTO PEDIDOS_PECAS (PEDIDOID, PECAID) VALUES (1, 1);
INSERT INTO PEDIDOS_PECAS (PEDIDOID, PECAID) VALUES (2, 2);
INSERT INTO PEDIDOS_PECAS (PEDIDOID, PECAID) VALUES (3, 3);
INSERT INTO PEDIDOS_PECAS (PEDIDOID, PECAID) VALUES (4, 4);


-- TABELA PARA INSERT DE DADOS EM PEDIDO POR ARRANJOS--
INSERT INTO PEDIDOS_ARRANJOS (PEDIDOID, ARRANJOID) VALUES (1, 1);
INSERT INTO PEDIDOS_ARRANJOS (PEDIDOID, ARRANJOID) VALUES (2, 2);
INSERT INTO PEDIDOS_ARRANJOS (PEDIDOID, ARRANJOID) VALUES (3, 3);
INSERT INTO PEDIDOS_ARRANJOS (PEDIDOID, ARRANJOID) VALUES (4, 4);


-- TABELA PARA INSERT DE DADOS EM RECIBOS--
INSERT INTO RECIBOS (PEDIDOID, VALOR) VALUES (1, 10.00);
INSERT INTO RECIBOS (PEDIDOID, VALOR) VALUES (2, 20.00);
INSERT INTO RECIBOS (PEDIDOID, VALOR) VALUES (3, 15.00);


---- TABELA PARA INSERT DE DADOS EM DEVOLUCOES--
INSERT INTO DEVOLUCOES (PEDIDOID, VALOR_REEMBOLSO) VALUES (3, 10.00);