CREATE DATABASE RETROSARIA
USE RETROSARIA 

-- DROPS--

DROP DATABASE RETROSARIA

DROP TABLE LOJAS
DROP TABLE PECAS
DROP TABLE ARRANJOS
DROP TABLE PEDIDOS
DROP TABLE PEDIDOS_PECAS
DROP TABLE PEDIDOS_ARRANJOS
DROP TABLE RECIBOS
DROP TABLE DEVOLUCOES

-- SE NECESSARIAS ALTERACOES NAS TABELAS, PREENCHER COM DADOS NECESSARIOS 
ALTER TABLE LOJAS
ALTER TABLE PECAS
ALTER TABLE ARRANJOS
ALTER TABLE PEDIDOS
ALTER TABLE PEDIDOS_PECAS
ALTER TABLE PEDIDOS_ARRANJOS
ALTER TABLE RECIBOS
ALTER TABLE DEVOLUCOES

--CRIAÇÃO DE TABELAS

-- tabela para Lojas
CREATE TABLE LOJAS (
    LOJAID INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(MAX) NOT NULL,
    MORADA NVARCHAR(MAX) NOT NULL,
    FUNCIONARIOS INT NOT NULL
);

-- tabela para pecas de vestuario
CREATE TABLE PECAS (
    PECAID INT PRIMARY KEY IDENTITY(1,1),
    TIPO NVARCHAR(MAX) NOT NULL,
    COR NVARCHAR(MAX) NOT NULL,
	TAMANHO NVARCHAR(MAX) NOT NULL,
	URGENCIA BIT NOT NULL
);

-- tabela para tipo de arranjos e o seu custo
CREATE TABLE ARRANJOS (
    ARRANJOID INT PRIMARY KEY IDENTITY(1,1),
    TIPO NVARCHAR(MAX) NOT NULL,
    CUSTO DECIMAL(10,2) NOT NULL,
);

-- tabela para pedidos feitos pelos clientes, inclui urgencia e se foram devolvidos
CREATE TABLE PEDIDOS (
    PEDIDOID INT PRIMARY KEY IDENTITY(1,1),
    LOJAID INT,
    CLIENTE NVARCHAR(MAX) NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE, 
    CONCLUIDO BIT NOT NULL,
    PAGO BIT NOT NULL,
    DEVOLVIDO BIT NOT NULL,
    OBSERVACOES NVARCHAR(MAX),
    FOREIGN KEY (LOJAID) REFERENCES LOJAS(LOJAID)
);

-- tabela para pedidos por peca
CREATE TABLE PEDIDOS_PECAS (
    PEDIDOID INT,
    PECAID INT,
    PRIMARY KEY (PEDIDOID, PECAID),
    FOREIGN KEY (PEDIDOID) REFERENCES PEDIDOS(PEDIDOID),
    FOREIGN KEY (PECAID) REFERENCES PECAS(PECAID)
);

-- tabela para pedidos por arranjo
CREATE TABLE PEDIDOS_ARRANJOS (
    PEDIDOID INT,
    ARRANJOID INT,
    PRIMARY KEY (PEDIDOID, ARRANJOID),
    FOREIGN KEY (PEDIDOID) REFERENCES PEDIDOS(PEDIDOID),
    FOREIGN KEY (ARRANJOID) REFERENCES ARRANJOS(ARRANJOID)
);

-- tabela para recibos emitidos
CREATE TABLE RECIBOS (
    RECIBOID INT PRIMARY KEY IDENTITY(1,1),
    PEDIDOID INT,
    VALOR DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (PEDIDOID) REFERENCES PEDIDOS(PEDIDOID)
);

-- tabela para devolucoes 
CREATE TABLE DEVOLUCOES (
    DEVOLUCAOID INT PRIMARY KEY IDENTITY(1,1),
    PEDIDOID INT,
    VALOR_REEMBOLSO DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (PEDIDOID) REFERENCES PEDIDOS(PEDIDOID)
);